import { HStack, Image, Text, VStack, Box, Hide, Heading, Grid, GridItem, Flex, Accordion, AccordionIcon, AccordionButton, AccordionPanel, AccordionItem} from "@chakra-ui/react"
import Head from "next/head"
import Navbar from "@/components/Navbar"
import Button from "@/components/Button"
import { BsChatLeftTextFill } from "react-icons/bs"

// Fonts
import "@fontsource/inter"
import "@fontsource/inter/600.css"
import "@fontsource/inter/800.css"
import "@fontsource/eb-garamond"
import "@fontsource/eb-garamond/600.css"

// Icons
import { BsArrowRight } from "react-icons/bs"
import HeroSlide from "@/components/Home/HeroSlide"
import Footer from "@/components/Footer"
import ChatBot from "@/components/ChatBot"

const Home = () => {
  return (
    <>
      <Head>
        <title>Brulee Patisserie | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className="slideshow">
        <div className="slides">
          <HeroSlide 
            slideBgColor="#9ED8EA" 
            imgSrc="./croissant.png" 
            heading="Discover Melbourne&apos;s Most Decadent Patisserie Treats."
            subHeading="Satisfy your sweet tooth with our heavenly selection of pastries, cakes, and macarons - all crafted with the finest ingredients and an artisan&apos;s touch."
            buttonContent="View Shop"
            href="/store"
          />
          <Flex
            direction={{ base: "column", md: "row" }}
            width="100vw"
            height="100vh"
            backgroundColor="#CF9249"
            overflow="hidden"
            display="flex"
            justifyContent="center"
            fontFamily="EB Garamond"
            alignItems="center"
          >
            <VStack width={{ base: "100%", md: "50%" }} height="100vh" bg="#9ED8EA" justify="center" paddingTop="4rem">
              <Text fontSize={{ base: "1.5rem" }} textAlign={{ base: "center" }} width={{ base: "70%", md: "90%", lg: "80%" }} fontWeight="800" color="white">
                  Crusty Delights Catered For You
              </Text>
              <Text width="60%" fontSize="1rem"  textAlign={{ base: "center", }} color="white" fontWeight="600">
                  Got a Function or Event? <br/>No Matter the Size, We&apos;ve Got You Covered.
                </Text>
              <Image fit="contain" width={{ base: "80%", lg: "60%" }} src="./vanilla-eclair.png" css={{ animation: `rotate 120s linear infinite` }} alt="vanilla eclair" zIndex="0"/>
              <Button content="View Catering" link="/catering" main="true" zIndex="99"/>
            </VStack>
            <VStack width="50%" bg="#CF9249" display={{ base: "none", md: "flex"}} align="center" justify="center" spacing="2rem" height="85vh" zIndex="2" paddingTop="2rem" id="error-img">
              <VStack spacing="0">
                <Image src="/croissant-2.svg" alt="float" height="10vh"/>
                <Text color="white" fontWeight="600" fontSize="2rem"><i>From Pastries, <u>With Love</u></i></Text>
              </VStack>
              <VStack width="60%" align="start" justify="center">
                <Image fit="contain" width="100%" src="./heroSlide-2.jpg" zIndex="1" border="white 2px solid" alt="hero"/>
              </VStack>
            </VStack>
          </Flex>
        </div>
      </div>
      <ChatBot/>
      <HStack height="100vh" spacing={0} width="100vw">
        <VStack width={{ base: "100%", md: "50%" }} height="100vh" padding="1rem" bg="#8E9F68" color="white" overflow="hidden" align="start">
          <Text fontSize="2.5rem" fontWeight="600">Our Story</Text>
          <Text fontSize="2rem">Chef Mariana Chedid</Text>
          <Text width="90%" fontSize={{ base: "0.75rem", md: "0.9rem", xl: "1.1rem" }}>
            Born and raised in Lebanon, Mariana migrated to Sydney Australia at the age of 18. In 2007, she moved to Melbourne and quickly fell in love with the culinary culture that the city had to offer.
            <br/>
            <br/>
            At the age of 27, inspired by the story of &apos;Julia Child&apos;, Mariana decided to pursue her dream of becoming a chef. She travelled to France to follow the footsteps of her idol.
            <br/>
            <br/>
            By 2014, Mariana had completed a comprehensive training program in Cuisine and Pâtisserie, and graduated with a &apos;Grand Diplôme&apos; from &apos;Le Cordon Bleu&apos; in Paris.
            <br/>
            <br/>
            Mariana then pursued another learning journey with Brasserie Thoumieux, under the mentorship of Chef Jean-Francois Piège.
            Mariana&apos;s culinary career started in Paris at the Michelin-starred restaurant &apos;La Tour D&apos;argent&apos;, under the supervision of Chef Yohan Lastre.
            <br/>
            <br/>
            Upon returning to Melbourne, she embarked on an exploration and experimentation journey using the finest local produce, ultimately enabling her to forge her own path within the culinary scene, finally founding &apos;Brûlée&apos; in 2020.
          </Text>
        </VStack>
        <Hide below="md">
          <Image fit="cover" height="100%" width="50%" alt="Chef Mariana Chedid" src="https://res.cloudinary.com/dr4hp76ea/image/upload/v1681565488/ezgif.com-webp-to-jpg_dqhnyj.jpg"/>
        </Hide>
      </HStack>
      <Footer/>
    </>
  )
}

export default Home